# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Default

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      mvn -version
      mvn package

      echo Listando arquivos na pasta de trabalho:
      dir C:\agent\_work\1\s\target
    displayName: 'Run Maven Package'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target'  # Caminho para a pasta onde o .jar é gerado
    ArtifactName: 'drop'     # Nome do artefato
    publishLocation: 'Container'